### ISSUE TITLE
making posts horizonal with pictures alternating side

### ISSUE THREAD

**Issue by bquast** [andrewbanchich/massively-jekyll-theme#1]
I think having an option to make the posts horizonal (on desktop), with pictures alternativing sides could be a great way to expand the theme.

An HTML5UP example of what I mean is Fractal:

https://html5up.net/fractal

**Comment by andrewbanchich** [comment]
that would be pretty cool! that is something i thing is more suited for a fork, though, since my goal is only to jekyllfy the static HTML themes by HTML5 UP and not modify their design.
