### ISSUE TITLE
Code segments do not highlight

### ISSUE THREAD

**Issue by bdoyle0182** [andrewbanchich/massively-jekyll-theme#3]
Hi Andrew,

My friend an I are currently working on a site and using markdown to display code does not seem to support the syntax highlighting feature i.e.

```java
import java.security.SecureRandom;
```

Thanks,
Brendan

**Comment by andrewbanchich** [comment]
Hi @bdoyle0182, which syntax highlighting feature are you referring to?

**Comment by bdoyle0182** [comment]
If we’re using markdown and create a code segment just like on github, the code isn’t colored. It could just be your theme, but kramdown should support it by default.

**Comment by andrewbanchich** [comment]
Yep, syntax highlighting is something the front end code would handle, not
Jekyll. Massively doesn't have support for that. I'm open to pull requests
though. ;)
